config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tours#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tours, except: [:new, :edit] do
    resources :broadcasts, only: [:new, :create]
    resources :events, only: [:create]
  end

  resources :notifications, only: :index
  resources :users, only: [:show, :update]
  resources :events, only: [:show, :update, :destroy]
end

app/views/layouts/modals/_modal_add_event.html.erb
<div class="modal fade" id="addEventModal" tabindex="-1" role="dialog" aria-labelledby="addEventModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>
      </div>
      <div class="modal-body">
        <div class="card card-body">
        <h1 class="pb-3"> Add Event </h1>
        <%= simple_form_for([@tour, @event]) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :venue, label: 'Venue' %>
            <%= f.input :city, label: 'City' %>
            <%= f.input :show_start_at,
              as: :datetime,
              label: 'Start Time',
              class: 'form-control-datetime',
              html5: true,
              input_html: { value: "#{ (DateTime.now.next_week.noon + 8.hours).strftime("%Y-%m-%d#{'T'}%H:%M:%S") }" }
            %>
            <%= f.input :schedule, class: 'schedule', as: :rich_text_area, label: 'Schedule', placeholder: '' %>
          </div>
        </div>

          <div class="modal-footer">
            <%= f.button :submit, class: 'btn btn-primary', value: 'Submit' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_add_tour.html.erb
<div class="modal fade" id="addTourModalNEW" tabindex="-1" role="dialog" aria-labelledby="addTourModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">

      <div class="modal-body">

        <button type="button" class="close" id="close-add-tour" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>

        <div class="d-flex justify-content-between modal-navigation">
          <a class="collapse-button" data-toggle="collapse" href="#multiCollapseAddTour" role="button" aria-expanded="false" aria-controls="multiCollapseAddTour">Step 1</a>
          <a class="collapse-button" data-toggle="collapse" href="#multiCollapseAddEvent" role="button" aria-expanded="false" aria-controls="multiCollapseAddEvent">Step 2</a>
          <a class="collapse-button" data-toggle="collapse" href="#multiCollapseAddMember" role="button" aria-expanded="false" aria-controls="multiCollapseAddMember">Step 3</a>
        </div>

        <%= simple_form_for(@tour) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="row">
            <div class="col">
              <div class="collapse show multi-collapse" id="multiCollapseAddTour">
                <div class="card card-body">
                  <div class="form-inputs">
                    <h1 class="pb-3"> Add Tour </h1>
                    <%= f.input :name, label: 'Tour Name' %>
                    <%= f.input :artist_name, label: 'Artist Name' %>
                    <%= f.input :logo, as: :file %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="collapse multi-collapse" id="multiCollapseAddEvent">
                <div class="card card-body">
                  <div class="form-inputs">
                    <h1 class="pb-3"> Add First Event </h1>
                    <%= f.simple_fields_for(:events) do |fe| %>
                      <%= render 'event_fields', f: fe %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="collapse multi-collapse" id="multiCollapseAddMember">
                <div class="card card-body scrollable">
                  <div class="form-inputs">
                    <h1 class="pb-3"> Invite Members </h1>
                    <%= fe.simple_fields_for(:tour_members) do |ftm| %>
                      <%= render 'tour_member_fields', f: ftm %>
                    <% end %>
                    <div class="links"><%= link_to_add_association 'Add a member', fe, :tour_members %></div>
                  <% end %>
                  </div>
                </div>
                    <div class="modal-footer">
                      <%= f.button :submit, class: 'btn btn-primary', value: 'Submit' %>
                    </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_edit_event.html.erb
<div class="modal fade" id="editEventModal" tabindex="-1" role="dialog" aria-labelledby="editEventModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-body">

        <button type="button" class="close" id="close-edit-event" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>

        <div class="d-flex justify-content-around modal-navigation">
          <a class="collapse-button" data-toggle="collapse" href="#multiCollapseEditEvent" role="button" aria-expanded="false" aria-controls="multiCollapseEditEvent">Edit Event</a>
          <a class="collapse-button" data-toggle="collapse" href="#multiCollapseEditMember" role="button" aria-expanded="false" aria-controls="multiCollapseEditMember">Manage Members</a>
        </div>

        <%= simple_form_for(@event) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="row">
            <div class="col">
              <div class="collapse show multi-collapse" id="multiCollapseEditEvent">
                <div class="card card-body">
                  <div class="form-inputs">
                      <%= f.input :venue, label: 'Venue' %>
                      <%= f.input :city, label: 'City' %>
                      <%= f.input :show_start_at, label: 'Start Time', html5: true %>
                      <%= f.input :schedule, as: :rich_text_area, label: 'Schedule', placeholder: '' %>
                  </div>
                  <div class="modal-footer">
                    <%= f.button :submit, class: 'btn btn-primary', value: 'Update event' %>
                    <%= link_to 'Delete this event', event_path(@event), method: :delete, class: 'btn delete-button' %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="collapse multi-collapse" id="multiCollapseEditMember">
                <div class="card card-body scrollable">
                  <div class="form-inputs">
                    <%= f.simple_fields_for(:tour_members) do |ftm| %>
                      <%= render 'tour_member_fields', f: ftm %>
                    <% end %>
                    <div class="links"><%= link_to_add_association 'Add a tour member', f, :tour_members %></div>

                  </div>
                </div>
                    <div class="modal-footer">
                      <%= f.button :submit, class: 'btn btn-primary', value: 'Update event' %>
                    </div>
              </div>
            </div>

          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_edit_member.html.erb
<!-- Edit Crew icon -->

<%= image_tag "icons/icon_crew_round.svg",
  class: 'icon-round',
  data:  { toggle: "modal",
   target: "#editMemberModal"
 } %>

<!-- Notif icon -->
 <%= link_to notifications_path do %>
   <%= image_tag "icons/icon_notif.svg", class: 'icon-round', id: 'notif' %>
 <% end %>

<!-- <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#editMemberModal">
  Edit the tour members
</button> -->

<div class="modal fade" id="editMemberModal" tabindex="-1" role="dialog" aria-labelledby="editMemberModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-header">
        <h5 class="modal-title" id="editMemberModalTitle">Edit Tour Members</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@tour) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.simple_fields_for(:tour_members) do |ftm| %>
              <%= render 'tour_member_fields', f: ftm %>
            <% end %>
          </div>
          <div class="links"><%= link_to_add_association 'Add a tour member', f, :tour_members %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
            <%= f.button :submit, class: 'btn btn-secondary btn-sm', value: "Edit Tour Members" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_edit_profile.html.erb
<div class="modal fade" id="editProfileModal" tabindex="-1" role="dialog" aria-labelledby="editProfileModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">

      <div class="modal-body">

        <button type="button" class="close" id="close-edit-profile" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>

        <div class="d-flex justify-content-around modal-navigation">
          <a class="collapse-button" data-toggle="collapse" href="#multiCollapseEditProfile" role="button" aria-expanded="false" aria-controls="multiCollapseEditProfile">General</a>
          <a class="collapse-button" data-toggle="collapse" href="#multiCollapseUploadAvatar" role="button" aria-expanded="false" aria-controls="multiCollapseUploadAvatar">Profile Picture</a>
          <a class="collapse-button" data-toggle="collapse" href="#multiCollapseEditSkill" role="button" aria-expanded="false" aria-controls="multiCollapseEditSkill">Skills</a>
        </div>

        <%= simple_form_for(@user) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="row">
            <div class="col">
              <div class="collapse show multi-collapse" id="multiCollapseEditProfile">
                <div class="card card-body">
                  <div class="form-inputs">
                    <%= f.input :full_name, label: 'Full Name', placeholder: "** required **"%>
                    <%= f.input :nickname, label: 'Nickname'%>
                    <%= f.input :email, label: 'Email' %>
                    <%= f.input :phone, label: 'Phone Number'%>
                    <%= f.input :description, label: 'Bio'%>
                  </div>
                  <div class="modal-footer">
                    <%= f.button :submit, class: 'btn btn-primary', value: 'Submit' %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="collapse multi-collapse" id="multiCollapseUploadAvatar">
                <div class="card card-body">
                  <div class="form-inputs">
                    <%= f.input :avatar, label: 'Profile Picture', as: :file %>
                  </div>
                  <div class="modal-footer">
                    <%= f.button :submit, class: 'btn btn-primary', value: 'Submit' %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="collapse multi-collapse" id="multiCollapseEditSkill">
                <div class="card card-body">
                  <div class="form-inputs">
                    <%= f.association :skills, collection: Skill.order('name ASC'), as: :check_boxes, label: 'Job skills:' %>

                    <div class="modal-footer">
                      <%= f.button :submit, class: 'btn btn-primary', value: 'Submit' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_edit_tour.html.erb
<div class="modal fade" id="editTourModal" tabindex="-1" role="dialog" aria-labelledby="editTourModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>
      </div>
      <div class="modal-body">
        <div class="card card-body">
          <h1 class="pb-3"> Edit Tour </h1>
          <%= simple_form_for(@tour) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-inputs">
              <%= f.input :name, label: 'Tour Name' %>
              <%= f.input :artist_name, label: 'Artist Name' %>
              <%= f.input :logo, as: :file %>
            </div>

            <div class="modal-footer">
              <%= f.button :submit, class: 'btn btn-primary' %>
              <%= link_to 'Delete this tour', tour_path(@tour), method: :delete, class: 'btn delete-button' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_manage_members_for_specific_event.html.erb
<div class="modal fade" id="editMemberModal" tabindex="-1" role="dialog" aria-labelledby="editMemberModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>
      <%= simple_form_for(@event) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      </div>
      <div class="form-inputs">
        <div class="card card-body">
          <div class="modal-body">
            <h1 class="pb-3"> Manage Members </h1>

              <%= f.simple_fields_for(:tour_members) do |ftm| %>
                <%= render 'tour_member_fields', f: ftm %>
              <% end %>
              <div class="links"><%= link_to_add_association 'Add a tour member', f, :tour_members %></div>
              <div class="modal-footer">
                <%= f.button :submit, class: 'btn btn-secondary', value: "Save Changes" %>
              </div>
            <% end %>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_new_broadcast.html.erb
<div class="modal fade" id="newBroadcastModal" tabindex="-1" role="dialog" aria-labelledby="newBroadcastModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>
      </div>
      <div class="modal-body">
        <div class="card card-body">
          <h1 class="pb-3"> Create Notification </h1>
          <%= simple_form_for([@tour, @broadcast]) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-inputs">
              <%= f.input :broadcastable_id, collection: @tour.events, label: 'To :', prompt: 'whole tour' %>
              <%= f.input :name, label: 'Title' %>
              <%= f.input :content, as: :rich_text_area %>
            </div>

            <div class="modal-footer">
              <%= f.button :submit, class: 'btn btn-primary', value: 'Send' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_notifications_index.html.erb
<div class="modal fade" id="notificationsIndexModal" tabindex="-1" role="dialog" aria-labelledby="notificationsIndexModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-header">
        <h2 class="modal-title" id="notificationsIndexModalTitle">Notifications</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>
      </div>
      <div class="modal-body">
        <%= render current_user.notifications %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_view_event_members.html.erb
<div class="modal fade" id="viewEventMembersModal" tabindex="-1" role="dialog" aria-labelledby="viewEventMembersModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>
      </div>
      <div class="modal-body">
        <h1 class="pb-3"> Event Members </h1>
        <% @uniq_tour_members.each do |tm| %>
          <div class="card-member ml-2">
            <div class="card-member-block">
              <div class="row">
                <div class="col-2" id="member">
                  <% if  tm.user.avatar.attached? %>
                      <%= cl_image_tag tm.user.avatar.key, crop: :fill, class: 'avatar-medium-bordered' %>
                    <!-- else pour image par défaut -->
                  <% else %>
                    <%= cl_image_tag("https://res.cloudinary.com/dli73zoz7/image/upload/v1659793675/anonymous-avatar-icon-25_r45hmv.png",
                      crop: :fill, 
                      class: 'avatar-medium-bordered')
                    %>
                  <% end %>
                </div>
                <div class="col-10" id="member-card">
                  <h3><strong> <%= link_to (tm.user.full_name ? tm.user.full_name : tm.user.email), user_path(tm.user) %> </strong></h3>
                  <p> <%= tm.job_title %> </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_modal_view_tour_members.html.erb
<div class="modal fade" id="viewTourMembersModal" tabindex="-1" role="dialog" aria-labelledby="viewTourMembersModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-content-color">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <%= image_tag "icons/icon_esc.svg", alt: "alttext", class: '' %>
        </button>
      </div>
      <div class="modal-body">
        <h1 class="pb-3"> Tour Members </h1>
        <% @uniq_tour_members.each do |tm| %>
          <div class="card-member ml-2">
            <div class="card-member-block">
              <div class="row">
                <div class="col-2" id="member">
                  <% if  tm.user.avatar.attached? %>
                      <%= cl_image_tag tm.user.avatar.key, crop: :fill, class: 'avatar-medium-bordered' %>
                    <!-- else pour image par défaut -->
                  <% else %>
                    <%= cl_image_tag("https://res.cloudinary.com/dli73zoz7/image/upload/v1659793675/anonymous-avatar-icon-25_r45hmv.png",
                      crop: :fill, 
                      class: 'avatar-medium-bordered')
                    %>
                  <% end %>
                </div>
                <div class="col-10" id="member-card">
                  <h3><strong> <%= link_to (tm.user.full_name ? tm.user.full_name : tm.user.email), user_path(tm.user) %> </strong></h3>
                  <p> <%= tm.job_title %> </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>