config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tours#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tours, except: [:new, :edit] do
    resources :broadcasts, only: [:new, :create]
    resources :events, only: [:create]
  end

  resources :notifications, only: :index
  resources :users, only: [:show, :update]
  resources :events, only: [:show, :update, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_icon_nav.html.erb
<div class="icon-nav">
  <% if (controller_name == "tours" && action_name == "show") %>
    <!-- =======TOURS SHOW PAGE ICONS====== -->
    <% if policy(@tour).show? %>

      <div class="tours-show">
        <% if policy(@tour).edit? %>
          <%= image_tag "icons/icon_w_plus.svg",
            id: 'plus',
            class: 'icon-round',
            data:  { toggle: "modal",
            target: "#addEventModal"
          } %>

          <%= image_tag "icons/icon_w_edit.svg",
             id: 'edit',
             class: 'icon-round',
             data:  { toggle: "modal",
              target: "#editTourModal"
          } %>
        <% end %>

        <%= image_tag "icons/icon_w_crew.svg",
           id: 'crew',
           class: 'icon-round',
           data:  { toggle: "modal",
            target: "#viewTourMembersModal"
        } %>

        <% if policy(@tour).edit? %>
          <%= image_tag "icons/icon_w_notif.svg",
             id: 'new-notif',
             class: 'icon-round',
             data:  { toggle: "modal",
              target: "#newBroadcastModal"
          } %>
        <% end %>

        <% if user_signed_in? %>
          <%= image_tag "icons/icon_w_bell.svg",
            id: 'notif',
            class: 'icon-round',
            data:  { toggle: "modal",
            target: "#notificationsIndexModal"
          } %>
        <% end %>

      </div>
    <% end %>

  <% elsif (controller_name == "events" && action_name == "show")%>
    <!-- =======EVENTS SHOW PAGE ICONS====== -->
    <div class="events-show">

      <% if policy(@tour).edit? %>

        <%= image_tag "icons/icon_w_edit.svg",
          id: 'edit',
          class: 'icon-round edit-event',
          data:  { toggle: "modal",
          target: "#editEventModal"
        } %>

        <%#= image_tag "icons/icon_w_crew.svg",
           id: 'crew',
           class: 'icon-round',
           data:  { toggle: "modal",
            target: "#viewEventMembersModal"
        } %>

        <!-- =========ADD IMAGE_TAG TO CREATE NEW NOTIF========== -->
        <%#= link_to 'Create new broadcast', new_tour_broadcast_path(@event.tour) %>
        <%= image_tag "icons/icon_w_notif.svg",
           id: 'new-notif',
           class: 'icon-round',
           data:  { toggle: "modal",
            target: "#newBroadcastModal"
        } %>
      <% end %>

      <% if user_signed_in? %>
        <%= image_tag "icons/icon_w_bell.svg",
          id: 'notif',
          class: 'icon-round',
          data:  { toggle: "modal",
          target: "#notificationsIndexModal"
        } %>
      <% end %>

    </div>

  <% elsif (controller_name == "users" && action_name == "show")%>
    <!-- =======USERS SHOW PAGE ICONS====== -->
    <div class="users-show">
      <% if policy(@user).edit? %>
        <%= image_tag "icons/icon_w_edit.svg",
          id: 'edit',
          class: 'icon-round edit-profile',
          data:  { toggle: "modal",
           target: "#editProfileModal"
         } %>
       <% end %>

      <% if user_signed_in? %>
        <%= image_tag "icons/icon_w_bell.svg",
          id: 'notif',
          class: 'icon-round',
          data:  { toggle: "modal",
          target: "#notificationsIndexModal"
         } %>
      <% end %>
    </div>

  <% elsif (controller_name == "tours" && action_name == "index") %>
    <!-- =======TOURS INDEX PAGE ICONS====== -->
    <div class="tours-index">
      <%= image_tag "icons/icon_w_plus.svg",
        id: 'plus',
        class: 'icon-round add-tour',
        data:  { toggle: "modal",
        target: "#addTourModalNEW"
       } %>

      <% if user_signed_in? %>
        <%= image_tag "icons/icon_w_bell.svg",
          id: 'notif',
          class: 'icon-round',
          data:  { toggle: "modal",
          target: "#notificationsIndexModal"
        } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logos/tourbook_logo_2.png" %>
  <% end %>


  <% if user_signed_in? %>
    <%= link_to user_path(current_user) do %>
      <% if current_user.avatar.present? %>
        <%= cl_image_tag current_user.avatar.key,
          crop: :fill,
          class: "avatar-bordered dropdown-toggle",
          id: "navbarDropdown",
          data: { toggle: "collapse",
          target: "#navbarSupportedContent" },
          'aria-haspopup': true,
          'aria-expanded': false
        %>
      <% else %>
        <%= image_tag "https://res.cloudinary.com/dli73zoz7/image/upload/v1659793675/anonymous-avatar-icon-25_r45hmv.png",
          class: "avatar-bordered dropdown-toggle",
          id: "navbarDropdown",
          data: { toggle: "collapse",
          target: "#navbarSupportedContent" },
          'aria-haspopup': true,
          'aria-expanded': false
        %>
      <% end %>
    <% end %>

  <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      </ul>
  <% end %>

</div>


  <%#= link_to 'notifs', notifications_path %>
  <%#= link_to notifications_path do %>
    <%#= image_tag "icons/icon_notif.svg", class: 'icon-round' %>
  <%# end %>